### ISSUE TITLE
unexpected umig requirement

### ISSUE THREAD

**Issue by sumeetoc** [terraform-google-modules/terraform-google-vm#110]
AFAIK [unmanaged instance group](https://cloud.google.com/compute/docs/instance-groups/creating-groups-of-unmanaged-instances) does not require any instance template, it just needs below parameters:
- Name
- Region and Zone
- Network and Subnetwork
- List of instances (falling under provided Subnetwork and Zone)

The current Terraform module to create unmanaged instance group is attached to an instance template resource which will create number of identical instances, this eliminates the definition of unmanaged instance group.

**Expected requirement** would be to collect instances ID to simply add it in the instance group which could be unidentical/not created via a common instance template

**Comment by morgante** [comment]
The goal of this module is to provide a common interface for managing VMs across multiple implementations.

If all you want to do is to group a few (existing) instances into an instance group, you should just use the [resource](https://www.terraform.io/docs/providers/google/r/compute_instance_group.html) directly.
