### ISSUE TITLE
Module does not accept auto_healing_policies

### ISSUE THREAD

**Issue by mandarmahajan** [terraform-google-modules/terraform-google-vm#124]
terraform keeps repeating that block is not expected. 

It seems auto_healing_policies is not declared or added to variables.tf .

Can someone confirm ?

I need autohealing to work for this module.

**Comment by bharathkkb** [comment]
Hi @mandarmahajan 
Could you show an example config, we do support `auto_healing_policies` via the [health checks](https://github.com/terraform-google-modules/terraform-google-vm/blob/63100169ebecea163f3965f4be3df8b600af047d/modules/mig/variables.tf#L90) created using the`var. health_check`
