### ISSUE TITLE
CentOS 6 EOL

### ISSUE THREAD

**Issue by xSAVIKx** [terraform-google-modules/terraform-google-vm#125]
The CentOS 6 has [reached](https://cloud.google.com/compute/docs/eol/centos6) its EOL and is no longer available as a GCE image.

Usually, it should not be an issue, but if for the `instance_template` module the `image_family` is set to empty string, terraform considers it as unset and falls back to the `centos-6` image family.

Such a fallback makes some pipelines fail with smth like this:
```
Error: error retrieving image information: googleapi: Error 404: The resource 'projects/centos-cloud/global/images/family/centos-6' was not found, notFound

  on .terraform/modules/sim-preemptible-template.vm_instance_template/modules/instance_template/main.tf line 25, in data "google_compute_image" "image_family":
  25: data "google_compute_image" "image_family" {
```

**Comment by bharathkkb** [comment]
@xSAVIKx thanks for the report. We should update the defaults set [here](https://github.com/terraform-google-modules/terraform-google-vm/blob/ae4d7777958fe4238d96191a3aa7c7deab996fd1/modules/instance_template/main.tf#L18). Happy to review a PR

**Comment by xSAVIKx** [comment]
@bharathkkb please check out the PR #126.
