### ISSUE TITLE
service_account should not be required for instance_template module

### ISSUE THREAD

**Issue by amontalban** [terraform-google-modules/terraform-google-vm#143]
Hi,

I want to create a template without a `service_account` attached to the instance.

According to the [docs](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance_template#service_account) this is an optional argument.

If you agree I can submit a PR.

Thanks!

**Comment by morgante** [comment]
If a service account is not provided, the default Google Compute Engine service account is used. This is not recommended as it is less secure.
