### ISSUE TITLE
Setting MIG update policy is not possible

### ISSUE THREAD

**Issue by stevereaver** [terraform-google-modules/terraform-google-vm#156]
Setting the update policy is broken, this is because all values are required by the module, such as;

`      type                         = "PROACTIVE"
      instance_redistribution_type = "PROACTIVE"
      minimal_action               = "REPLACE"
      max_surge_fixed              = 0
      max_surge_percent            = 20
      max_unavailable_fixed        = 2
      max_unavailable_percent      = 0
      min_ready_sec                = 50
      replacement_method           = "RECREATE"`

However some of the values are conflicting, max_surge_percent conflicts with max_surge_fixed, and max_unavailable_fixed conflicts with  max_unavailable_percent, making it impossible to run the terraform apply.

**Comment by morgante** [comment]
You should be able to set the values you don't want to use to `null`.

**Comment by stevereaver** [comment]
Thanks, I just solved my own issue. Setting conflicting values to null works, as;

`update_policy = [
    {
      type                         = "OPPORTUNISTIC"
      instance_redistribution_type = "PROACTIVE"
      minimal_action               = "REPLACE"
      max_surge_percent            = null
      max_surge_fixed              = 10
      max_unavailable_percent      = null
      max_unavailable_fixed        = 0
      min_ready_sec                = 50
      replacement_method           = "RECREATE"
    }
  ]`
