### ISSUE TITLE
Add instance labels to disk

### ISSUE THREAD

**Issue by mouglou** [terraform-google-modules/terraform-google-vm#157]
Hi there !

We face an issue with our cost allocation on GCP. 

Here the bug.
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance#boot_disk

When we create an instance on GCE with Terrraform, the disk doesn't get the labels that we give to the instance. There is no "labels" option in the "boot_disk" section.
To get that you must create a seperate disk, add labels on it, and attach it to the instance.

But not everybody want to deal with the disk management. If we need a simple instance, we are just calling the google_compute_instance resource.

Is there a way to add the same labels that you give to your instance to the disk during the deployment ? Or can it be add to the provider/resource ?

Why I asking this ? Because in the billing section of Google, when you sort by labels on Compute service, I can't see the cost of my drive. If my instance have a label "application=mariadb" the disk doesn't have it. We see this: 
[Charges for other usage]

Thanks for your help !

**Comment by morgante** [comment]
This is not the provider repo.

**Comment by mouglou** [comment]
Oh ok sorry. I was thinking that was more linked to the module than the provider. I will open it on the provider so.
Thanks @morgante
