### ISSUE TITLE
Error: Output refers to sensitive values

### ISSUE THREAD

**Issue by pixrl** [terraform-google-modules/terraform-google-vm#163]
Hello I have a little problem with this module. Here is my Terraform version:
```
terraform version
Terraform v0.15.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v3.65.0
+ provider registry.terraform.io/hashicorp/google-beta v3.65.0
```
I am getting following error when I am trying to run `terraform plan -destroy`:
```
╷
│ Error: Output refers to sensitive values
│
│   on .terraform/modules/vm_compute_instance/modules/compute_instance/outputs.tf line 22:
│   22: output "instances_details" {
│
│ Expressions used in outputs can only refer to sensitive values if the sensitive attribute is true.
╵
```
I was able to search for this in terraform documentation: https://learn.hashicorp.com/tutorials/terraform/sensitive-variables#reference-sensitive-variables

When I added `sensitive   = true` to `instances_details` on ` .terraform/modules/vm_compute_instance/modules/compute_instance/outputs.tf` the problem is gone.
```
...
output "instances_details" {
  description = "List of all details for compute instances"
  value       = google_compute_instance_from_template.compute_instance.*
  sensitive   = true
}
...
```

I was wondering if it should be added to the [modules/compute_instance/outputs.tf](https://github.com/terraform-google-modules/terraform-google-vm/blob/master/modules/compute_instance/outputs.tf). Let me know what you think. I am just starting my journey with Terraform.

**Comment by morgante** [comment]
Yes that is the correct fix.
