### ISSUE TITLE
Need to create instance template for a single VM instance?

### ISSUE THREAD

**Issue by PePoDev** [terraform-google-modules/terraform-google-vm#184]
As my topic, If I need to create a single VM in Google cloud. I should create an instance template?

What's the reason behind the design?

**Comment by morgante** [comment]
The goal is to encourage consistency across different mechanisms of creating instances, so if you need to switch from a single instance to a UMIG or MIG you can do so seamlessly without rewriting your config substantially.

**Comment by PePoDev** [comment]
@morgante Thanks for answering.

Does this mean I should recreate my instance always when I change the machine type in an instance template?

**Comment by morgante** [comment]
@PePoDev Yes you generally need to recreate the instance when updating the instance template.

**Comment by PePoDev** [comment]
@morgante It's possible to add a new submodule for a single VM instance?

I think it's easy to change instance size without recreating the instance.

**Comment by morgante** [comment]
We probably don't want to create a new submodule, but if you're saying updating the instance size isn't working properly that's a bug.

**Comment by vin116** [comment]
hi Morgante, PePoDev, 
I am facing same issue when change optional parameter in vm template => recreate instance that I don't expect.

Regardsm
vin

**Comment by pavars** [comment]
In some cases instance size might grow and you want to increase the actual disk for the instance not the template which is used by other instances as well. There are quite a bunch variables like hostname, disk size, delete_disks, network tags etc, that could be instance specific but cannot be defined there. Are there any plans to include them in the future to compute_instance?
