### ISSUE TITLE
Remove redundant network, subnetwork and subnetwork_project variables in MIG

### ISSUE THREAD

**Issue by denissimonovski** [terraform-google-modules/terraform-google-vm#185]
Remove redundant network, subnetwork and subnetwork_project variables in MIG module. They sit in the variables.tf but they are not used in the MIG module.

**Comment by denissimonovski** [comment]
I can do this btw, if allowed?

**Comment by morgante** [comment]
PRs are welcome.

**Comment by denissimonovski** [comment]
@morgante Could you please review the above PR?

**Comment by morgante** [comment]
Thanks for the contribution.
