### ISSUE TITLE
Corner case: instance_template tries to replace resources

### ISSUE THREAD

**Issue by amontalban** [terraform-google-modules/terraform-google-vm#188]
Hi team 👋 ,

I'm having a strange corner case that unfortunately can't build a reproducible code that can be shared.

This is the situation, I have a codebase with multiple instances of `instance_template` and `mig` modules that build a cluster (Each pair of `instance_template`/`mig` builds a specific type of node).

If I try to modify some parameters of the cluster or even adding a completely new component that uses the same `source_image` it tries to update all instances of `instance_template` due to a newer version of the `source_image`.

This is what I see when that happens:

```
  # module.worker_instance_template[1].google_compute_instance_template.tpl must be replaced
+/- resource "google_compute_instance_template" "tpl" {
      ~ id                   = "projects/qa-project/global/instanceTemplates/cluster-andres-dev-data-0-b-20210714213103100800000004" -> (known after apply)
      ~ metadata_fingerprint = "qC1GeP8EDh8=" -> (known after apply)
      ~ name                 = "cluster-andres-dev-data-0-b-20210714213103100800000004" -> (known after apply)
      ~ project              = "qa-project" -> (known after apply)
      + region               = (known after apply)
      ~ self_link            = "https://www.googleapis.com/compute/beta/projects/qa-project/global/instanceTemplates/cluster-andres-dev-data-0-b-20210714213103100800000004" -> (known after apply)
        tags                 = [
            "cluster-andres-dev",
            "cluster-andres-dev-worker",
        ]
      + tags_fingerprint     = (known after apply)
        # (5 unchanged attributes hidden)

      + confidential_instance_config {
          + enable_confidential_compute = (known after apply)
        }

      ~ disk {
          ~ device_name       = "persistent-disk-0" -> (known after apply)
          ~ interface         = "SCSI" -> (known after apply)
          - labels            = {} -> null
          ~ mode              = "READ_WRITE" -> (known after apply)
          - resource_policies = [] -> null
          ~ source_image      = "projects/images-project/global/images/cluster-20210408145250" -> (known after apply) # forces replacement
            # (5 unchanged attributes hidden)
        }
```

The theory I have is that for some reason it is trying to use `image_family ` data source instead of `image` data source and therefore is forcing a replacement (Because there is a newer version).

In my variables file I have defined (And these are not changed between executions):

- `source_image_project`
- `source_image_family`
- `source_image`

There is an broader output available at: https://gist.github.com/amontalban/b2d6f78b5f442ef04a4d6458cb824305

I have reviewed the [code](https://github.com/terraform-google-modules/terraform-google-vm/blob/master/modules/instance_template/main.tf#L37) and looks like it is doing what it should so I don't understand what is going on.

If you have any pointer of what could be wrong I would highly appreciate it.

Thank you very much!

**Comment by morgante** [comment]
Unfortunately without reproducible code it's going to be hard for us to help debug.

**Comment by amontalban** [comment]
> Unfortunately without reproducible code it's going to be hard for us to help debug.

@morgante I understand, unfortunately, I couldn't write an easily reproducible code.

But I did some tests and what is affecting is the data sources, so I created #190 that removes them and uses the format for [source_image](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance_template#source_image).

What do you think?

Thanks!
