### ISSUE TITLE
missing tags in main.tf modules 

### ISSUE THREAD

**Issue by hpuri** [terraform-google-modules/terraform-google-vm#196]
Added "  subnetwork_project = var.project_id" at lines 26 and 35 to terraform-google-vm/examples/compute_instance/simple/main.tf

module.instance_template.google_compute_instance_template.tpl: Creating...
╷
│ Error: cannot determine self_link for subnetwork "cft-vm-test-x4ia": network_interface.0.subnetwork_project: required field is not set
│ 
│   with module.instance_template.google_compute_instance_template.tpl,
│   on ../../../modules/instance_template/main.tf line 57, in resource "google_compute_instance_template" "tpl":
│   57: resource "google_compute_instance_template" "tpl" {

**Comment by stenalpjolly** [comment]
@hpuri Can you please provide some more information on the above. Maybe a snippet block? 
It is expected to provide subnetwork along with subnetwork_project
