### ISSUE TITLE
Add autogen templates to reduce duplicate code

### ISSUE THREAD

**Issue by namusyaka** [terraform-google-modules/terraform-google-vm#24]
As morgante mentioned it in #19, mig and mig-with-percent share the most code. To avoid the one side change, I also think we need to add the checkscript not to forget the change shared codes between mig and mig-with-percent.

**Comment by morgante** [comment]
Actually, I'd like to autogen both modules from the same source. Like the [GKE module](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/autogen).
