### ISSUE TITLE
MIG module: RegionInstanceGroupManager is forced to be re-created on every provision

### ISSUE THREAD

**Issue by ivankorn** [terraform-google-modules/terraform-google-vm#28]
That causes resource already exist API error on every subsequent provision attempt: 

```
Error: Error creating RegionInstanceGroupManager: googleapi: Error 409: The resource 'projects/gl-ivankorniienko-seed-251912/regions/us-west1/instanceGroupManagers/multi-mig-lb-http-group1-mig' already exists, alreadyExists

  on .terraform/modules/mig1/terraform-google-modules-terraform-google-vm-cb3d6cc/modules/mig/main.tf line 32, in resource "google_compute_region_instance_group_manager" "mig":
  32: resource "google_compute_region_instance_group_manager" "mig" {



Error: Error creating RegionInstanceGroupManager: googleapi: Error 409: The resource 'projects/gl-ivankorniienko-seed-251912/regions/us-east1/instanceGroupManagers/multi-mig-lb-http-group2-mig' already exists, alreadyExists

  on .terraform/modules/mig2/terraform-google-modules-terraform-google-vm-cb3d6cc/modules/mig/main.tf line 32, in resource "google_compute_region_instance_group_manager" "mig":
  32: resource "google_compute_region_instance_group_manager" "mig" {

```

**Comment by ogreface** [comment]
Running into this as well.

**Comment by pksmall** [comment]
Hello.

I plunged into this bug so much that I created a test project (https://github.com/pksmall/terraform-google-lb-http-mig).

@ivankorn described the bug in as much detail as possible and I repeated it on my environment:

`$ TF_VAR_group1_size=0 terraform apply
...
  # module.mig1.google_compute_region_instance_group_manager.mig must be replaced
+/- resource "google_compute_region_instance_group_manager" "mig" {
        base_instance_name        = "multi-mig-lb-http-group1"
      ~ distribution_policy_zones = [
          - "europe-west3-a",
          - "europe-west3-b",
          - "europe-west3-c",
        ] -> (known after apply) # forces replacement
...
           ~ target_size               = 2 -> 0

          + auto_healing_policies {
             + initial_delay_sec = 0
           }

...
  # module.mig2.google_compute_region_instance_group_manager.mig must be replaced
+/- resource "google_compute_region_instance_group_manager" "mig" {
        base_instance_name        = "multi-mig-lb-http-group2"
      ~ distribution_policy_zones = [
          - "us-east1-b",
          - "us-east1-c",
          - "us-east1-d",
        ] -> (known after apply) # forces replacement
...
     + auto_healing_policies {
          + initial_delay_sec = 0
        }
...

Error: Error creating RegionInstanceGroupManager: googleapi: Error 409: The resource 'projects/operating-bolt-254712/regions/us-west1/instanceGroupManagers/multi-mig-lb-http-group3-mig' already exists, alreadyExists

  on ../terraform-google-vm/modules/mig/main.tf line 33, in resource "google_compute_region_instance_group_manager" "mig":
  33: resource "google_compute_region_instance_group_manager" "mig" {
`
Changes to the local variable **distribution_policy_zones** result in a forced replacement and change with every apply.

There was a fix to this bug, I thought, but it’s not. Log with edits from @evkuzin:
`
  # module.mig1.google_compute_region_instance_group_manager.mig must be replaced
+/- resource "google_compute_region_instance_group_manager" "mig" {
        base_instance_name        = "multi-mig-lb-http-group1"
      ~ distribution_policy_zones = [
          - "europe-west3-a",
          - "europe-west3-b",
          - "europe-west3-c",
        ] -> (known after apply) # forces replacement

Error: Error creating RegionInstanceGroupManager: googleapi: Error 409: The resource 'projects/operating-bolt-254712/regions/us-west1/instanceGroupManagers/multi-mig-lb-http-group3-mig' already exists, alreadyExists

  on ../terraform-google-vm/modules/mig/main.tf line 33, in resource "google_compute_region_instance_group_manager" "mig":
  33: resource "google_compute_region_instance_group_manager" "mig" {
`
Equally, almost only::
`
          + auto_healing_policies {
             + initial_delay_sec = 0
           }
`
it has become dynamic.

With my fix log:
`
..
 # module.mig1.google_compute_region_instance_group_manager.mig will be updated in-place
  ~ resource "google_compute_region_instance_group_manager" "mig" {
        base_instance_name        = "multi-mig-lb-http-group1"
        distribution_policy_zones = [
            "europe-west3-a",
            "europe-west3-b",
            "europe-west3-c",
        ]

 ~ target_size               = 2 -> 0
...
Apply complete! Resources: 0 added, 3 changed, 0 destroyed.

Outputs:

load-balancer-ip = 34.102.215.73

$ ./test.sh 
+ set -e
++ terraform output load-balancer-ip
+ URL=http://34.102.215.73
+ status=0
+ count=0
+ [[ 0 -lt 720 ]]
+ [[ 0 -ne 200 ]]
+ echo 'INFO: Waiting for load balancer...'
INFO: Waiting for load balancer...
++ curl -sf -m 5 -o /dev/null -w '%{http_code}' http://34.102.215.73
+ status=200
+ (( count=count+1 ))
+ sleep 5
+ [[ 1 -lt 720 ]]
+ [[ 200 -ne 200 ]]
+ [[ 1 -lt 720 ]]
+ echo 'INFO: PASS'
INFO: PASS
`
Bingo. It's worked. And as described in readme we got a response from group#2.

Pull request on the way. Thank you.

p.s. My apologies for the long comment :)
