### ISSUE TITLE
Support public IPs

### ISSUE THREAD

**Issue by ocervell** [terraform-google-modules/terraform-google-vm#3]
Does this module support public IP ? We'd need an `access_config` block in the VM's `network_interface` for this to happen.
If we want to support both, I suggest looking at the Forseti VM [code](https://github.com/terraform-google-modules/terraform-google-forseti/blob/4b93f517dd0d89cbc11a0d2605cce03a65e90d58/modules/client/main.tf#L37) as it took me a while to figure it out.

**Comment by aaron-lane** [comment]
We should indeed support the ability to choose public or private IP addresses.

**Comment by aaron-lane** [comment]
This will need to be changed in:

- `instance_template`
- `preemptible_and_regular_instance_templates`
