### ISSUE TITLE
Getting exception: use google beta provider for MIG module

### ISSUE THREAD

**Issue by arvindpai** [terraform-google-modules/terraform-google-vm#4]
Error: module.mig.google_compute_instance_group_manager.default: "auto_healing_policies": [REMOVED] This field is in beta. Use it in the the google-beta provider instead. See https://terraform.io/docs/providers/google/provider_versions.html for more details.

**Comment by aaron-lane** [comment]
@arvindpai @morgante I've transferred the issue to the VM module.

**Comment by aaron-lane** [comment]
Actually, `google_compute_instance_group_manager.default` doesn't appear to exist in this repository, or any of our repositories for that matter. 😅 

@arvindpai please reopen this if you can provide more context.
