### ISSUE TITLE
MIG - Update policy cannot be created

### ISSUE THREAD

**Issue by ocervell** [terraform-google-modules/terraform-google-vm#41]
There is an issue with the `update_policy` variable: it requires all fields to be set, but if you set all the fields (see 1.), the API will give you an error. If you set only API-required fields (see 2.), the module gives an error

1. Passing all arguments:

```hcl
module "squid-mig" {
  source              = "terraform-google-modules/vm/google//modules/mig"
  version             = "~> 1.0"
  ...
  update_policy = [{
    type                         = "PROACTIVE"
    instance_redistribution_type = "PROACTIVE"
    minimal_action               = "REPLACE"
    max_surge_fixed              = 2
    max_unavailable_fixed        = 2
    max_unavailable_percent      = 0
    max_surge_percent            = 0
    min_ready_sec                = 100
  }]
}
```

Fails with:
![Screenshot 2019-11-13 at 19 47 34](https://user-images.githubusercontent.com/9629314/68794034-7f3ad800-064e-11ea-8ec8-4e6c7a1970a1.png)

2. Passing only API-required arguments:
```
module "squid-mig" {
  source              = "terraform-google-modules/vm/google//modules/mig"
  version             = "~> 1.0"
  region              = var.region
  project_id          = module.squid-project.project_id
  instance_template   = module.squid-mig-template.self_link
  hostname            = "squid-${var.region}"
  autoscaling_enabled = true
  autoscaling_cpu = [
    {
      target = 0.95
    }
  ]
  min_replicas           = 4
  tcp_healthcheck_enable = true
  named_ports = [{
    name = "tcp"
    port = 3128
  }]
  hc_port = 80
  update_policy = [{
    type                         = "PROACTIVE"
    instance_redistribution_type = "PROACTIVE"
    minimal_action               = "REPLACE"
    max_unavailable_percent      = 0
    max_surge_percent            = 0
    min_ready_sec                = 100
  }]
}
```
fails with:
![Screenshot 2019-11-13 at 19 49 14](https://user-images.githubusercontent.com/9629314/68794142-b315fd80-064e-11ea-8623-4fc27b6d0ea6.png)

**Comment by morgante** [comment]
What happens if you set the undesired fields to null?

```
module "squid-mig" {
  source              = "terraform-google-modules/vm/google//modules/mig"
  version             = "~> 1.0"
  ...
  update_policy = [{
    type                         = "PROACTIVE"
    instance_redistribution_type = "PROACTIVE"
    minimal_action               = "REPLACE"
    max_surge_fixed              = null
    max_unavailable_fixed        = null
    max_unavailable_percent      = 0
    max_surge_percent            = 0
    min_ready_sec                = 100
  }]
}
```

**Comment by shd4** [comment]
> What happens if you set the undesired fields to null?
> 
> ```
> module "squid-mig" {
>   source              = "terraform-google-modules/vm/google//modules/mig"
>   version             = "~> 1.0"
>   ...
>   update_policy = [{
>     type                         = "PROACTIVE"
>     instance_redistribution_type = "PROACTIVE"
>     minimal_action               = "REPLACE"
>     max_surge_fixed              = null
>     max_unavailable_fixed        = null
>     max_unavailable_percent      = 0
>     max_surge_percent            = 0
>     min_ready_sec                = 100
>   }]
> }
> ```

 null  -  worked for me, Thank you!
