### ISSUE TITLE
Error reading instance template

### ISSUE THREAD

**Issue by ocervell** [terraform-google-modules/terraform-google-vm#46]
I'm running into an error when running a second apply: the instance template name doesn't match a regex that seems to assume the name should be between 0 and 19 characters. 

Since there is a string containing the date appended to the `name_prefix` input, it's something that I cannot control.

The first apply works fine (creation), but the second apply fails (read):

```
Error: Error reading Instance Template "squid-europe-west1-20191125171408399700000001": googleapi: Error 400: Invalid value 'projects/rnm-hostedsvcs-comsvcs-sq7051/global/instanceTemplates/squid-europe-west1-20191125171408399700000001'. Values must match the following regular expression: '[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?|[1-9][0-9]{0,19}', invalidParameter
```

```
Error: Error reading Instance Template "squid-europe-west4-20191125171408472600000002": googleapi: Error 400: Invalid value 'projects/rnm-hostedsvcs-comsvcs-sq7051/global/instanceTemplates/squid-europe-west4-20191125171408472600000002'. Values must match the following regular expression: '[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?|[1-9][0-9]{0,19}', invalidParameter
```

**Comment by morgante** [comment]
This sounds like a provider issue, not a module issue.

**Comment by m-bodmer** [comment]
I had a similar issue when I was running when my google provider version was `provider.google: version = "~> 2.16"`

I had to delete my projects `.terraform` folder, rerun `terraform init` to get `provider.google: version = "~> 3.4"` and everything worked as expected.

**Comment by jioblack** [comment]
I had a similar issue and noticed i had a space after my project id
example instead of let's say:  
project = "my-project-id"   I wrote 
project = "my-project-id "

The space after the id caused the problem. After removing it everything worked perfectly
