### ISSUE TITLE
MIG Module - Empty Autohealing policy requires a terraform apply on each invocation 

### ISSUE THREAD

**Issue by wripley** [terraform-google-modules/terraform-google-vm#51]
In the mig module, it defaults to creating an autohealing policy because the initial delay seconds will default to 0 when you do not pass in any value ([module main.tf](https://github.com/terraform-google-modules/terraform-google-vm/blob/master/modules/mig/main.tf#L58)). Every time you run a plan, terraform tries to change add the policy to the mig.

**Comment by morgante** [comment]
Can you describe more about the desired outcome? I'm a little confused on the error you're seeing and why it would be a permadiff.

Should the default be no autohealing at all?

**Comment by wripley** [comment]
The desired outcome is that terraform would not suggest a change to the MIG every time I apply. I am not specifying autohealing, but that one variable (initial delay seconds) is causing the definition to show up in the module (which is essentially an empty policy). The provider should ideally complain that it won't create an auto healing policy since it does not have enough of the information, but the module should also not create it by default.

Auto healing should be optional according to [tf docs](https://www.terraform.io/docs/providers/google/r/compute_region_instance_group_manager.html#auto_healing_policies).

**Comment by mandarmahajan** [comment]
terraform does not accept the 
auto_healing_policies block. keeps repeating block is not expected. 

any suggestions?

**Comment by trisha0996** [comment]
> terraform does not accept the auto_healing_policies block. keeps repeating block is not expected.
> 
> any suggestions?

Getting the same error. How must I reference the auto_healing_policies block?
