### ISSUE TITLE
compute_instance module only works if project_id is configured at the provider level

### ISSUE THREAD

**Issue by apsureda** [terraform-google-modules/terraform-google-vm#60]
Data source:

```
data "google_compute_zones" "available" {
}
```

in submodule modules/compute_instance/main.tf does not take the project id as parameter. Which leads to the following error when using this module in a configuration where the project id is not configured at the provider level:

```
Error: project: required field is not set

  on .terraform/modules/compute_instance/terraform-google-modules-terraform-google-vm-a8795e3/modules/compute_instance/main.tf line 31, in data "google_compute_zones" "available":
  31: data "google_compute_zones" "available" {
```

The project ID needs to be exposed as an optional variable in the module as it is the case in other submodules (mig, instance_template).

**Comment by morgante** [comment]
Could we actually grab the project ID from the template variable?
