### ISSUE TITLE
Attaching public IP to instance.

### ISSUE THREAD

**Issue by chanux** [terraform-google-modules/terraform-google-vm#80]
The instance_template allows allocating a list of IPs via `access_config` parameter. But it's not clear to me how to attach an IP form that list to the instance. I can do that from the GCP Console after creating the instance but is it possible to do that from Terraform?

If I pass the same list of of IPs to `static_ips` parameter on compute_instance sub module, it'd complain
> Requested internal IP is outside the subnetwork CIDR range

Any help is appreciated.

**Comment by morgante** [comment]
Are you trying to use a reserved external IP?

**Comment by chanux** [comment]
@morgante Yes. Pretty much the same thing as [this example](https://github.com/terraform-google-modules/terraform-google-vm/blob/master/examples/instance_template/simple/main.tf) shows.

**Comment by rchenzheng** [comment]
This is solved by this https://github.com/terraform-google-modules/terraform-google-vm/pull/83
