### ISSUE TITLE
In "mig" module, append `-vm` to `base_instance_name` 

### ISSUE THREAD

**Issue by AdamMAtWork** [terraform-google-modules/terraform-google-vm#87]
In the 'mig' module, we have:

```hcl
resource "google_compute_region_instance_group_manager" "mig" {
  base_instance_name = var.hostname
  name   = "${var.hostname}-mig"
}
```
In the `instance_template` module, the template name can be given a nice name as well, via the name_prefix variable:

```hcl
resource "google_compute_instance_template" "tpl" {
  name_prefix             = "${var.name_prefix}-"
}
```

But, the naming template for VM instances is tied to the name of the MIG, and cannot be named in a similar manner

If I provide a value of `backend` for "hostname", I end up with:

- A MIG named `backend-mig`, which is nice
- A VM template named `backend-vm-template-nnnnnnnnnnnnnnnn`, if that's what I want
- VM instances named `backend-xxxx`, which is not so nice and I cannot adjust

It would be nice if the base_instance_name would be set as 
```hcl
  base_instance_name = "${var.hostname}-vm"
```
so that my vm instances have names like:
- `backend-vm-nnnn`

An explicit prefix variable would also do the trick.

**Comment by morgante** [comment]
While your naming convention involves this, others might not include `-vm` in the name.

My suggestion would be adding a `name_suffix` variable to the MIG module which would could add `-vm` to the hostname. I'd be happy to review a PR adding that.

**Comment by TJonesy** [comment]
I made a PR that should satisfy both my use case and your use case I think. It allows overriding the name of the mig to be different from the hostname.
